export const MIN_APPOINTMENT_TITLE_LENGTH = 4
export const MAX_APPOINTMENT_TITLE_LENGTH = 64

export const MAX_APPOINTMENT_DESCRIPTION_LENGTH = 254

export const MIN_APPOINTMENT_DURATION_LENGTH = 30 // FORTNIGHT
export const MAX_APPOINTMENT_DURATION_LENGTH = 20160 // FORTNIGHT

export const MIN_APPOINTMENT_DATE_LENGTH = 20
export const MAX_APPOINTMENT_DATE_LENGTH = 25

export const MIN_APPOINTMENT_URL_LENGTH = 30
export const MAX_APPOINTMENT_URL_LENGTH = 384

export const MIN_APPOINTMENT_LATITUDE_LENGTH = -90
export const MAX_APPOINTMENT_LATITUDE_LENGTH = 90

export const MIN_APPOINTMENT_LONGITUDE_LENGTH = -180
export const MAX_APPOINTMENT_LONGITUDE_LENGTH = 180

export const DEFAULT_APPOINTMENT_LIST_LIMIT = 10
